//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BananasAndPeaches.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Material
    {
        public int id { get; set; }
        [DisplayName("Name")]
        public string name { get; set; }
        [DisplayName("Description")]
        public string description { get; set; }
        [DisplayName("Already Got")]
        public bool alreadyGot { get; set; }
        [DisplayName("Price")]
        public Nullable<decimal> price { get; set; }
        [DisplayName("Task Step")]
        public int taskStepId { get; set; }
    
        public virtual TaskStep TaskStep { get; set; }
    }
}
