//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BananasAndPeaches.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskListDatabaseEntities : DbContext
    {
        public TaskListDatabaseEntities()
            : base("name=TaskListDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<TaskStep> TaskSteps { get; set; }
        public virtual DbSet<TaskToDo> TaskToDoes { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
    }
}
