//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BananasAndPeaches.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TaskToDo
    {
        public TaskToDo()
        {
            this.TaskSteps = new HashSet<TaskStep>();
        }
    
        public int id { get; set; }
        [DisplayName("Task Name")]
        public string name { get; set; }
        [DisplayName("Description")]
        public string description { get; set; }
        [DisplayName("Due Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dueDate { get; set; }
        public bool isDone { get; set; }
        [DisplayName("Budget Estimate")]
        [DisplayFormat(DataFormatString = "{0:0.0}")]
        public Nullable<decimal> budgetEstimate { get; set; }
        //[DisplayName("Category")]
        public int categoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<TaskStep> TaskSteps { get; set; }
    }
}
