//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BananasAndPeaches.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TaskStep
    {
        public TaskStep()
        {
            this.Materials = new HashSet<Material>();
            this.Tools = new HashSet<Tool>();
        }
    
        public int id { get; set; }
        [DisplayName("Step Name")]
        public string name { get; set; }
        [DisplayName("Description")]
        public string description { get; set; }
        [DisplayName("Time Required")]
        [DisplayFormat(DataFormatString = "{0:0.0}")]
        public Nullable<decimal> timeRequired { get; set; }
        public bool isDone { get; set; }
        [DisplayName("Task Name")]
        public int taskId { get; set; }
        [DisplayName("Step Priority")]
        public int stepPriority { get; set; }
        //[DisplayName("Tools")]
        //public int tools { get; set; }
    
        public virtual ICollection<Material> Materials { get; set; }
        public virtual TaskToDo TaskToDo { get; set; }
        public virtual ICollection<Tool> Tools { get; set; }
    }
}
