//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BananasAndPeaches.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Tool
    {
        public Tool()
        {
            this.TaskSteps = new HashSet<TaskStep>();
        }
    
        public int id { get; set; }
        [DisplayName("Name")]
        public string name { get; set; }
        [DisplayName("Description")]
        public string description { get; set; }
        [DisplayName("Already Got")]   
        public bool alreadyGot { get; set; }
        [DisplayName("Supplier")]
        public string supplier { get; set; }
         [DisplayName("Cost")]
        public Nullable<decimal> cost { get; set; }
       
        public virtual ICollection<TaskStep> TaskSteps { get; set; }
    }
}
